### ISSUE TITLE
Feature Requests, in order of priority

### ISSUE THREAD

**Issue by 685Degrees** [bit-by-bit-coding/bxb-website#1]
Can you...

Important for functionality:
- add to Covid policy as specified via the Slack
- add a sign up button and a volunteer button to the home page
- add a volunteer page with the blurb already written for the volunteers (it's in the drive)
- reorder the nav bar so it goes Home FAQ About Volunteer and then Sign Up (with different formatting for the Sign Up button to draw attention to it)
- add a donation button
- SEO?

Design:
- Update to match the current color scheme? All the svgs used have been redesigned in the new scheme and are uploaded to the drive, so it should be a relatively quick fix.
- make the nav bar a little thicker?
- restore the animation I had on the nav buttons, where they scale instead of turning color? At least speed up the current transition?
- make the font on the FAQ accordion panel titles smaller and restore the animation I had on them?
- change the font on the sign up button (on the sign up page) to Nunito and decrease the font height? And generally adjust the button to have a higher width:height aspect ratio than it currently does (ie make it shorter)?
- change my bio to read "I’m Selena Zhang; I'm an avid web developer and love to teach and learn from others! Next year, I plan to study computer science at MIT, but in eighth grade, I was the only girl in my computer science class, and I felt discouraged and alienated. I want other girls to have a different experience, so I’ve devoted hundreds of hours to teaching after-school programs throughout high school."
- maybe move the photos on the homepage down after the details section?

**Comment by MoralCode** [comment]
> make the nav bar buttons scale slightly instead of turning color

 this is being replaced by #35
