### ISSUE TITLE
Graph banner on home page is in front of text

### ISSUE THREAD

**Issue by Form-And-Function** [bit-by-bit-coding/bxb-website#22]
I want the text in front of the banner, please

**Comment by MoralCode** [comment]
looks like the signup page has this same issue too and was not fixed in #40 because it uses a separate scss file.

![Screenshot_20200623_110731](https://user-images.githubusercontent.com/17362949/85439602-0683ee80-b542-11ea-81bf-7ef57368010c.png)

**Comment by sophiaaaaa** [comment]
I just made another pull request
