### ISSUE TITLE
Sign up button too small on mobile

### ISSUE THREAD

**Issue by Form-And-Function** [bit-by-bit-coding/bxb-website#23]
I just feel it ought to be larger (bigger font and maybe wider). Ignore the inspect element on here. IDK why that kept popping up when I tried to screenshot.
![bitbybitcoding org_index html(iPhone X)](https://user-images.githubusercontent.com/29594993/84585452-ce074680-adc4-11ea-802d-cc9c697a5016.png)

**Comment by EnneNerdyPerson** [comment]
![image](https://user-images.githubusercontent.com/67206137/85647312-09223900-b653-11ea-9d45-6b4fbc59d29c.png)
Is this a good size?
