### ISSUE TITLE
Update the site to reflect that we have moved online!!!!

### ISSUE THREAD

**Issue by Form-And-Function** [bit-by-bit-coding/bxb-website#25]
Remove the location. Remove references to snacks and providing laptops. Change duration to be from 2 to 4. Remove the need to purchase tickets. Instead, have a recommended $30 donation.

**Comment by MoralCode** [comment]
it seems like there's a lot of deleting of major content...
- should the location/map on the homepage be replaced with anything?
- seems like we're deleting a lot of information that we'll just need to add back again for next year (like FAQ's and stuff if my assumption of your request to delete al references to the things you mentioned is correct).


Also:
- RE: donation. I'm assuming we are reusing the same paypal link
- these kinds of updates that apply just to this year may be better suited to a blog post? that's a larger and slightly irrelevant discussion rn tho.
