### ISSUE TITLE
Change suggested donation on homepage to $35

### ISSUE THREAD

**Issue by 685Degrees** [bit-by-bit-coding/bxb-website#38]

**Comment by joonaskinnunen** [comment]
I'll work on this.

**Comment by MoralCode** [comment]
@685Degrees I believe the exact amount for this was also made in the same meeting that tackled #26. there may be some discussion in that recording of why the $30 number was picked.

Regardless, has the signup page also been checked to make sure this value is updated? I think the $30 number was also added to that page as well
