### ISSUE TITLE
Make header shorter and logo bigger on mobile

### ISSUE THREAD

**Issue by MoralCode** [bit-by-bit-coding/bxb-website#41]
![image](https://user-images.githubusercontent.com/17362949/85884138-00d31680-b797-11ea-96ce-f6a8f6ffcdf8.png)

**Comment by sophiaaaaa** [comment]
nooo I committed my changes under the wrong branch, it's under getinvolved-patch now, sorry

**Comment by MoralCode** [comment]
It doesn't look like there are any changes to the site header on that branch (which i think got superseded by #66 anyway). do you have these changes somewhere?

**Comment by sophiaaaaa** [comment]
I forgot what exactly happened but I'll fix it after we finish major updates
