### ISSUE TITLE
Modify our footer to include our mission statement/donate/contact -- something like this

### ISSUE THREAD

**Issue by 685Degrees** [bit-by-bit-coding/bxb-website#58]
<img width="1279" alt="Screen Shot 2020-06-29 at 1 40 44 PM" src="https://user-images.githubusercontent.com/42020514/86054012-3e8da480-ba0e-11ea-82b5-a31c328e8e37.png">

**Comment by lucas-28** [comment]
Just worked on making flexbox divs for the footer and committed some basic changes to the footer branch. I'll finish the second part in the next few days.

**Comment by MoralCode** [comment]
do we want to add a guidestar badge too (since your screenshot includes badges?)
